# Generated by Django 3.0.8 on 2020-08-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('recordeddate', models.DateField(blank=True, null=True)),
                ('numcases', models.IntegerField(blank=True, null=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('countyname', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'counties',
                'managed': False,
            },
        ),
    ]
