# Generated by Django 3.0.7 on 2020-07-06 02:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Casesbydate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('getnumcases', django.contrib.postgres.fields.jsonb.JSONField()),
                ('recordeddate', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'casesbydate',
                'managed': False,
            },
        ),
    ]
