# Generated by Django 3.0.8 on 2020-07-29 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_casesbydate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Casesbydate',
        ),
    ]
