# Generated by Django 3.0.7 on 2020-06-28 22:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recordeddate', models.DateField(blank=True, null=True)),
                ('numcases', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Counties',
            fields=[
                ('countyname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('geog', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={
                'db_table': 'counties',
                'managed': False,
            },
        ),
    ]
